export const transactionsList: Transaction[] = [
    {
      id: "txn_01",
      $id: "unique_id_01",
      name: "Coffee Shop",
      paymentChannel: "in-store",
      type: "purchase",
      accountId: "acc_01",
      amount: 5.75,
      pending: false,
      category: "Food and Drink",
      date: "2024-08-24",
      image: "https://example.com/images/coffee.jpg",
      $createdAt: "2024-08-24T12:34:56Z",
      channel: "physical",
      senderBankId: "bank_01",
      receiverBankId: "bank_02",
    },
    {
      id: "txn_02",
      $id: "unique_id_02",
      name: "Online Bookstore",
      paymentChannel: "online",
      type: "purchase",
      accountId: "acc_02",
      amount: 29.99,
      pending: false,
      category: "Books",
      date: "2024-08-23",
      image: "https://example.com/images/books.jpg",
      $createdAt: "2024-08-23T15:22:10Z",
      channel: "digital",
      senderBankId: "bank_03",
      receiverBankId: "bank_04",
    },
    {
      id: "txn_03",
      $id: "unique_id_03",
      name: "Grocery Store",
      paymentChannel: "in-store",
      type: "purchase",
      accountId: "acc_03",
      amount: 45.23,
      pending: true,
      category: "Groceries",
      date: "2024-08-22",
      image: "https://example.com/images/groceries.jpg",
      $createdAt: "2024-08-22T08:45:33Z",
      channel: "physical",
      senderBankId: "bank_05",
      receiverBankId: "bank_06",
    },
    {
      id: "txn_04",
      $id: "unique_id_04",
      name: "Streaming Service",
      paymentChannel: "online",
      type: "subscription",
      accountId: "acc_04",
      amount: 12.99,
      pending: false,
      category: "Entertainment",
      date: "2024-08-21",
      image: "https://example.com/images/streaming.jpg",
      $createdAt: "2024-08-21T14:12:45Z",
      channel: "digital",
      senderBankId: "bank_07",
      receiverBankId: "bank_08",
    },
    {
      id: "txn_05",
      $id: "unique_id_05",
      name: "Electricity Bill",
      paymentChannel: "online",
      type: "bill",
      accountId: "acc_05",
      amount: 85.50,
      pending: false,
      category: "Utilities",
      date: "2024-08-20",
      image: "https://example.com/images/electricity.jpg",
      $createdAt: "2024-08-20T10:55:01Z",
      channel: "digital",
      senderBankId: "bank_09",
      receiverBankId: "bank_10",
    }
  ];
  